import 'bootstrap/dist/css/bootstrap.css'
import 'font-awesome/css/font-awesome.css'

import 'components/common/IconLabel/IconLabel.stories'
import 'components/common/Sider/Sider.stories'
import 'components/common/ElireCarousel/ElireCarousel.stories'
import 'components/common/Nav/Nav.stories'
import 'components/common/InputForm/InputForm.stories'
import 'components/common/TimeLine/TimeLine.stories'
import 'components/common/ElireRemoteSelect/ElireRemoteSelect.stories'
import 'components/common/Indicateur/Indicateur.stories'
import 'components/common/Charts/Charts.stories'
import 'components/common/Toolbar/ElireTable.stories'
